BEGIN;

DROP TABLE IF EXISTS account;
DROP TABLE IF EXISTS invoice CASCADE;
DROP TABLE IF EXISTS invoice_item;

DROP TYPE IF EXISTS account_level CASCADE;
DROP TYPE IF EXISTS pay_status CASCADE;
DROP TYPE IF EXISTS process_status CASCADE;

COMMIT;