BEGIN;
CREATE TABLE IF NOT EXISTS popup (
    id SERIAL NOT NULL,
    image TEXT,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    start_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
