services:
  topup:
    build: .
    container_name: topup
    env_file:
      - ./.env
    restart: always
    ports:
      - 3000:3000
  caddy:
    image: caddy:2.6.2
    container_name: caddy
    restart: always
    network_mode: "host"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-config:/config
      - ./caddy-data:/data
    environment:
      LOG_FILE: "/data/access.log"
